; EXIF Extension Configuration
; https://www.php.net/manual/en/exif.configuration.php
;
; To disable this extension, comment out the line below.
extension=exif

; Encoding for User Comments (default: empty = system default)
;exif.encode_unicode = ISO-8859-15

; Encoding for decoding Unicode User Comments (default: UTF-8)
exif.decode_unicode_motorola = UCS-2BE
exif.decode_unicode_intel = UCS-2LE

; Encoding for JIS strings (default: empty)
;exif.encode_jis =
;exif.decode_jis_motorola = JIS
;exif.decode_jis_intel = JIS
