{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zappzarapp.fullname" . }}-rabbitmq
  namespace: {{ include "zappzarapp.namespace" . }}
  labels:
    {{- include "zappzarapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.port }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "zappzarapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }}
